telegram_dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: rebki123
      port: 5432
      dbname: postgres
      schema: analytics
      threads: 4
